"use client";
import { useState } from "react";
import { Check, FileDown, Plus, X } from "lucide-react";
import { MANAGER_CRITERIA, RATING_LABELS, canReviewAppraisal, type DevelopmentAction, type SelfReview } from "@/lib/appraisalEngine";
import type { AppraisalDetail, AppraisalWorkspaceData, Command } from "./types";
import { stageLabels } from "./types";
import AppraisalDialog from "./AppraisalDialog";
import styles from "./appraisal.module.css";

export default function AppraisalReview({data,detail,command,busy,error,onClose,onDirty}:{data:AppraisalWorkspaceData;detail:AppraisalDetail;command:Command;busy:boolean;error:string;onClose:()=>void;onDirty:()=>void}) {
  const {row,snapshot}=detail;
  const person=data.people.find(p=>p.id===row.employee_id)!;
  const reviewer=data.people.find(p=>p.id===row.reviewer_id);
  const mine=row.employee_id===data.viewer.id, manager=canReviewAppraisal(data.viewer.id,row);
  const released=["released","acknowledged"].includes(row.workflow_status);
  const editable=(data.viewer.isHr||manager)&&!mine&&["self_review","manager_review"].includes(row.workflow_status)&&data.cycle?.status!=="closed";
  const [tab,setTab]=useState(mine&&!released?"reflection":manager&&row.workflow_status==="manager_review"?"manager":"evidence");
  const [self,setSelf]=useState<SelfReview>(row.self_assessment??{achievements:"",challenges:"",support:""});
  const [ratings,setRatings]=useState(row.manager_assessment?.ratings??[0,0,0,0,0]);
  const [notes,setNotes]=useState(row.manager_assessment?.notes??"");
  const [plan,setPlan]=useState<DevelopmentAction[]>(row.manager_assessment?.development??[{title:"",dueDate:"",owner:"employee",status:"planned"}]);
  const [rating,setRating]=useState(3),[rationale,setRationale]=useState("");
  const [response,setResponse]=useState(row.employee_response??"");
  const [reason,setReason]=useState("");
  const [selectedPeers,setSelectedPeers]=useState<string[]>([]);
  const [newReviewer,setNewReviewer]=useState(row.reviewer_id??"");
  const [metric,setMetric]=useState<"add_goal"|"add_kpi"|null>(null);
  const [metricForm,setMetricForm]=useState({title:"",weight:1,progress:0,target:100,actual:0,unit:"%",direction:"higher"});
  const [confirm,setConfirm]=useState<"manager_submit"|"release"|"self_submit"|null>(null);
  const act:Command=(action,payload)=>command(action,payload,row.id,row.revision);
  const managerPayload={ratings,notes,development:plan};
  const canCalibrate=data.viewer.isHr&&!mine&&!manager;
  return <section id="appraisal-review" className={styles.review}>{error && <div className={styles.error} role="alert">{error}</div>}
    <div className={styles.reviewHeader}><div><div className={styles.eyebrow}>Individual review / {data.cycle?.name}</div><h2>{person.name}</h2><p className={styles.muted}>{person.role||"Role not set"} · {person.department||"No department"}<br />Reviewer: {reviewer?.name??"Unassigned"}</p></div><div className={styles.row}><span className={styles.badge} data-stage={row.workflow_status}>{stageLabels[row.workflow_status]}</span>{released&&<button className={styles.button} onClick={()=>window.print()}><FileDown size={14} />Print / PDF</button>}<button className={styles.small} onClick={onClose} aria-label="Close employee review"><X size={15} /></button></div></div>
    <div className={`${styles.stepper} ${styles.noPrint}`}>{Object.entries(stageLabels).map(([key,label])=><span data-active={key===row.workflow_status} key={key}>{label}</span>)}</div>
    {released&&row.calibration&&<div className={styles.notice}><strong>Final assessment: {RATING_LABELS[row.calibration.rating-1]}</strong><p>{row.calibration.rationale}</p><p className={styles.muted}>Released {new Date(row.released_at!).toLocaleString()}. The evidence snapshot remains fixed; development actions can continue.</p></div>}
    <div className={styles.reviewGrid}><div className={styles.stack}>
      <div className={`${styles.tabs} ${styles.noPrint}`} style={{flexWrap:"wrap"}}>{[["evidence","Evidence"],["reflection","Employee reflection"],...(!mine||released?[["manager","Manager assessment"]]:[]),["development","Development"],["activity","Activity"]].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
      {tab==="evidence"&&<section className={styles.panel}><h3>Evidence behind the review</h3><p className={styles.muted}>{row.evidence_snapshot?`Frozen at manager sign-off · ${new Date(snapshot.capturedAt).toLocaleString()}`:"Live evidence, scoped to this employee and performance period. Manager sign-off freezes the record."}</p>
        <h3 className="mt-6">Objectives</h3>{snapshot.goals.map(g=><div className={styles.evidenceItem} key={g.id}><strong>{g.title}</strong><p>{g.percent_complete??"No"}% achieved · weight {g.weight??0}</p><div className={styles.progress}><span style={{width:`${Math.max(0,Math.min(100,g.percent_complete??0))}%`}} /></div></div>)}{!snapshot.goals.length&&<p className={styles.notice}>No objectives linked to this cycle.</p>}
        {editable&&<><button className={styles.small} onClick={()=>setMetric("add_goal")}><Plus size={12} />Add objective</button>{detail.availableGoals.length>0&&<label className={styles.field}>Link an existing objective<select aria-label="Link existing objective" value="" disabled={busy} onChange={e=>{if(e.target.value)void act("link_goal",{id:e.target.value});}}><option value="">Choose an employee objective</option>{detail.availableGoals.map(g=><option value={g.id} key={g.id}>{g.title} ({g.cycle||"unassigned cycle"})</option>)}</select></label>}</>}
        <h3 className="mt-6">Key performance indicators</h3>{snapshot.kpis.map(k=><div className={styles.evidenceItem} key={k.id}><strong>{k.name}</strong><p>Actual {k.current_value??"—"} / target {k.target_value??"—"} {k.unit} · {k.measure_direction==="lower"?"Lower is better":"Higher is better"} · weight {k.weight??0}</p></div>)}{!snapshot.kpis.length&&<p className={styles.notice}>No KPIs linked to this cycle.</p>}
        {editable&&<><button className={styles.small} onClick={()=>setMetric("add_kpi")}><Plus size={12} />Add KPI</button>{detail.availableKpis.length>0&&<label className={styles.field}>Link an existing KPI<select aria-label="Link existing KPI" value="" disabled={busy} onChange={e=>{if(e.target.value)void act("link_kpi",{id:e.target.value});}}><option value="">Choose an employee KPI</option>{detail.availableKpis.map(k=><option value={k.id} key={k.id}>{k.name} ({k.cycle||"unassigned cycle"})</option>)}</select></label>}</>}
        <h3 className="mt-6">Work reports</h3><p className={styles.muted}>{snapshot.reporting.submitted} of {snapshot.reporting.expected} completed reporting periods covered. {snapshot.reporting.excused} periods excused for approved leave or no scheduled weekdays.</p>
        {snapshot.reports.map(r=><details className={styles.evidenceItem} key={r.id}><summary>{r.report_type} report · {r.period_end||r.submitted_at.slice(0,10)}</summary><p><strong>Accomplishments</strong><br />{r.accomplishments||"Not recorded"}</p><p><strong>Blockers</strong><br />{r.blockers||"None recorded"}</p><p><strong>Support requested</strong><br />{r.support_needed||"None recorded"}</p></details>)}
        {!snapshot.reports.length&&<p className={styles.notice}>No work reports recorded for this performance period.</p>}
      </section>}
      {tab==="reflection"&&<section className={styles.panel}><h3>The employee’s perspective</h3><p className={styles.muted}>Capture achievements, context and support needs. Self-ratings do not inflate the weighted performance score.</p>
        {mine&&row.workflow_status==="self_review"&&["active","review"].includes(data.cycle?.status??"")?<fieldset disabled={busy} onChangeCapture={onDirty}>
          {([["achievements","What did you achieve, and what evidence supports it?"],["challenges","What affected delivery or made the work harder?"],["support","What support or development would help next?"]] as const).map(([key,label])=><label className={styles.field} key={key}>{label}<textarea maxLength={8000} value={self[key]} onChange={e=>setSelf({...self,[key]:e.target.value})} /></label>)}
          <div className={styles.actions}><button className={styles.button} onClick={()=>act("self_save",self)}>Save reflection</button><button className={styles.primary} onClick={()=>setConfirm("self_submit")}>Submit to reviewer</button></div>
        </fieldset>:row.self_assessment?<div>{Object.entries(row.self_assessment).map(([key,value])=><div className={styles.evidenceItem} key={key}><strong className="capitalize">{key}</strong><p>{value||"Not provided"}</p></div>)}</div>:<p className={styles.notice}>The employee has not saved a reflection yet. It opens when HR activates the cycle.</p>}
        {manager&&row.workflow_status==="manager_review"&&<div className={styles.noPrint}><label className={styles.field}>Request clarification<textarea maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain what the employee should clarify or add." /></label><button className={styles.button} disabled={busy||reason.trim().length<10} onClick={()=>act("return_to_employee",{reason})}>Return to employee</button></div>}
      </section>}
      {tab==="manager"&&<section className={styles.panel}><h3>Manager assessment</h3><p className={styles.muted}>Rate observable work against agreed expectations. Consider constraints and the evidence across the whole period.</p>
        {manager&&row.workflow_status==="manager_review"?<fieldset disabled={busy} onChangeCapture={onDirty}><div className={styles.rubric}>{MANAGER_CRITERIA.map((criterion,i)=><label key={criterion}>{criterion}<select aria-label={criterion} value={ratings[i]} onChange={e=>setRatings(ratings.map((n,j)=>i===j?Number(e.target.value):n))}><option value={0}>Choose rating</option>{RATING_LABELS.map((label,j)=><option key={label} value={j+1}>{j+1} · {label}</option>)}</select></label>)}</div>
          <label className={styles.field}>Evidence and review conversation<textarea value={notes} maxLength={8000} onChange={e=>setNotes(e.target.value)} placeholder="Explain the ratings with specific examples, achievements and context." /></label>
          <h3 className="mt-5">Development commitments</h3>{plan.map((a,i)=><div className={styles.notice} key={i}><label className={styles.field}>Action {i+1}<input value={a.title} maxLength={500} onChange={e=>setPlan(plan.map((p,j)=>i===j?{...p,title:e.target.value}:p))} placeholder="A concrete action and intended outcome" /></label><div className={styles.grid2}><label className={styles.field}>Due date<input type="date" value={a.dueDate} onChange={e=>setPlan(plan.map((p,j)=>i===j?{...p,dueDate:e.target.value}:p))} /></label><label className={styles.field}>Owner<select aria-label={`Owner for action ${i+1}`} value={a.owner} onChange={e=>setPlan(plan.map((p,j)=>i===j?{...p,owner:e.target.value as "employee"|"manager"}:p))}><option value="employee">Employee</option><option value="manager">Manager</option></select></label></div>{plan.length>1&&<button className={styles.small} onClick={()=>setPlan(plan.filter((_,j)=>j!==i))}>Remove action</button>}</div>)}
          <button className={styles.small} disabled={plan.length>=10} onClick={()=>{onDirty();setPlan([...plan,{title:"",dueDate:"",owner:"employee",status:"planned"}]);}}>Add development action</button>
          <div className={styles.actions}><button className={styles.button} onClick={()=>act("manager_save",managerPayload)}>Save manager draft</button><button className={styles.primary} disabled={data.cycle?.status!=="review"} onClick={()=>setConfirm("manager_submit")}>Sign off for calibration</button></div>
          {data.cycle?.status!=="review"&&<p className={styles.notice}>Draft now. HR opens the review stage after the performance period ends.</p>}
        </fieldset>:row.manager_assessment?<><div className={styles.rubric}>{MANAGER_CRITERIA.map((criterion,i)=><div className={styles.evidenceItem} key={criterion}><strong>{criterion}</strong><p>{row.manager_assessment!.ratings[i]||"Not rated"} / 5</p></div>)}</div><p className={`${styles.notice} whitespace-pre-wrap`}>{row.manager_assessment.notes||"No notes yet"}</p></>:<p className={styles.notice}>The assigned reviewer completes this after the employee submits their reflection.</p>}
        {row.workflow_status==="calibration"&&canCalibrate&&<fieldset className={styles.noPrint} disabled={busy} onChangeCapture={onDirty}><h3 className="mt-6">HR calibration & release</h3><p className={styles.muted}>Review consistency and evidence. No forced ranking or automatic promotion, pay or employment recommendation is applied.</p><label className={styles.field}>Final rating<select aria-label="Final rating" value={rating} onChange={e=>setRating(Number(e.target.value))}>{RATING_LABELS.map((label,i)=><option key={label} value={i+1}>{i+1} · {label}</option>)}</select></label><label className={styles.field}>Calibration rationale<textarea value={rationale} maxLength={8000} onChange={e=>setRationale(e.target.value)} placeholder="Explain the final assessment and any difference from the manager’s view." /></label><div className={styles.actions}><button className={styles.button} disabled={rationale.trim().length<10} onClick={()=>act("return_to_manager",{reason:rationale})}>Return to manager</button><button className={styles.primary} onClick={()=>setConfirm("release")}>Review release</button></div></fieldset>}
        {row.workflow_status==="calibration"&&data.viewer.isHr&&!canCalibrate&&<p className={styles.notice}>Another HR administrator must calibrate this review. You cannot release your own appraisal or one you authored as reviewer.</p>}
      </section>}
      {tab==="development"&&<section className={styles.panel}><h3>Development & follow-through</h3><p className={styles.muted}>Keep commitments visible after the review conversation. Progress updates do not alter the signed-off score.</p>{row.development_plan.length?row.development_plan.map((a,i)=><div className={styles.evidenceItem} key={i}><strong>{a.title}</strong><p>Owner: {a.owner==="employee"?person.name:reviewer?.name} · due {a.dueDate}</p><label className={styles.field}>Action status<select aria-label={`Status for ${a.title}`} disabled={busy||!released||(!mine&&!manager)} value={a.status} onChange={e=>act("development",{index:i,status:e.target.value})}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="complete">Complete</option></select></label></div>):<p className={styles.notice}>The reviewer creates development commitments with the manager assessment.</p>}
        {mine&&row.workflow_status==="released"&&<fieldset disabled={busy} onChangeCapture={onDirty}><label className={styles.field}>Employee response (optional)<textarea value={response} maxLength={4000} onChange={e=>setResponse(e.target.value)} placeholder="Add your perspective, including anything you disagree with." /></label><p className={styles.muted}>Acknowledgement records that you received the review. It does not mean you agree with the rating.</p><button className={`${styles.primary} mt-4`} onClick={()=>act("acknowledge",{response})}>Acknowledge receipt</button></fieldset>}
        {row.acknowledged_at&&<div className={styles.notice}>Acknowledged {new Date(row.acknowledged_at).toLocaleString()}<p>{row.employee_response||"No additional employee comment."}</p></div>}
      </section>}
      {tab==="activity"&&<section className={styles.panel}><h3>Review history</h3><div className={styles.history}>{detail.events.map((e,i)=><p key={i}>{e.action.replaceAll("_"," ")}<small>{new Date(e.created_at).toLocaleString()}</small>{e.reason&&<small>{e.reason}</small>}</p>)}</div></section>}
      <div className={styles.printOnly}><h3>Employee reflection</h3><p>{row.self_assessment?.achievements}</p><p>{row.self_assessment?.challenges}</p><p>{row.self_assessment?.support}</p><h3>Manager assessment</h3><p>{row.manager_assessment?.notes}</p><h3>Development commitments</h3>{row.development_plan.map((a,i)=><p key={i}>{a.title} · {a.owner} · {a.dueDate} · {a.status}</p>)}</div>
    </div><aside className={styles.stack}>
      <section className={styles.panel}><div className={styles.eyebrow}>{row.evidence_snapshot?"Signed-off evidence score":"Evidence coverage"}</div><div className={styles.score}>{row.evidence_snapshot?row.total_score??"—":`${snapshot.coverage}%`}</div><p className={styles.muted}>{row.evidence_snapshot?"Weighted score / 100. HR’s final assessment is recorded separately.":"Of the cycle’s weighted inputs available. Missing evidence is never scored as zero."}</p>{snapshot.components.map(c=><div className={styles.component} key={c.key}><div className={styles.row} style={{justifyContent:"space-between"}}><strong>{c.label}</strong><span className={styles.badge}>{c.weight}%</span></div><p>{c.weight===0?"Not weighted":c.score===null?"Awaiting evidence":`${c.score} / 100`}</p><p>{c.detail}</p></div>)}</section>
      {editable&&<section className={`${styles.panel} ${styles.noPrint}`}><h3>Peer perspective</h3><p className={styles.muted}>Assign colleagues who observed this person’s work. Individual responses and comments are not shown in the appraisal.</p><div className="mt-3 space-y-2">{data.people.filter(p=>p.id!==row.employee_id&&p.id!==row.reviewer_id).map(p=>{const assignment=detail.peers.find(a=>a.reviewer_id===p.id);return <label className="flex items-center gap-2 text-xs" key={p.id}><input type="checkbox" disabled={busy||Boolean(assignment)} checked={Boolean(assignment)||selectedPeers.includes(p.id)} onChange={e=>setSelectedPeers(e.target.checked?[...selectedPeers,p.id]:selectedPeers.filter(id=>id!==p.id))} />{p.name}{assignment?<span className={styles.muted}>{assignment.submitted_at?"Submitted":"Assigned"}</span>:null}</label>;})}</div><button className={`${styles.button} mt-4`} disabled={busy||!selectedPeers.length} onClick={()=>act("assign_peers",{reviewerIds:selectedPeers})}>Assign selected peers</button></section>}
      {data.viewer.isHr&&editable&&<section className={`${styles.panel} ${styles.noPrint}`}><h3>Review ownership</h3><label className={styles.field}>Assigned reviewer<select aria-label="Assigned reviewer" value={newReviewer} onChange={e=>setNewReviewer(e.target.value)}>{data.people.filter(p=>p.id!==row.employee_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className={styles.muted}>Changing the reviewer clears their unsent draft and records the reassignment.</p><button className={`${styles.small} mt-3`} disabled={busy||newReviewer===row.reviewer_id} onClick={()=>act("assign_reviewer",{reviewerId:newReviewer})}>Update reviewer</button></section>}
    </aside></div>
    <AppraisalDialog error={error} open={metric!==null} title={metric==="add_goal"?"Add an objective":"Add a KPI"} busy={busy} onClose={()=>setMetric(null)}><form onSubmit={e=>{e.preventDefault();if(metric)void act(metric,metricForm).then(ok=>{if(ok)setMetric(null);});}}><p className={styles.muted}>Add {metric==="add_goal"?"an objective":"a KPI"} for {person.name} in this performance cycle.</p><label className={styles.field}>Title<input required minLength={3} maxLength={200} value={metricForm.title} onChange={e=>setMetricForm({...metricForm,title:e.target.value})} /></label><label className={styles.field}>Relative weight<input type="number" min={0} max={100} required value={metricForm.weight} onChange={e=>setMetricForm({...metricForm,weight:Number(e.target.value)})} /></label>{metric==="add_goal"?<label className={styles.field}>Completion (%)<input type="number" min={0} max={100} required value={metricForm.progress} onChange={e=>setMetricForm({...metricForm,progress:Number(e.target.value)})} /></label>:<><div className={styles.grid2}><label className={styles.field}>Target<input type="number" step="any" min={0} required value={metricForm.target} onChange={e=>setMetricForm({...metricForm,target:Number(e.target.value)})} /></label><label className={styles.field}>Actual<input type="number" step="any" min={0} required value={metricForm.actual} onChange={e=>setMetricForm({...metricForm,actual:Number(e.target.value)})} /></label></div><div className={styles.grid2}><label className={styles.field}>Unit<input value={metricForm.unit} maxLength={40} onChange={e=>setMetricForm({...metricForm,unit:e.target.value})} /></label><label className={styles.field}>Direction<select aria-label="KPI direction" value={metricForm.direction} onChange={e=>setMetricForm({...metricForm,direction:e.target.value})}><option value="higher">Higher is better</option><option value="lower">Lower is better</option></select></label></div></>}<button className={styles.primary} disabled={busy}>Save to employee evidence</button></form></AppraisalDialog>
    <AppraisalDialog error={error} open={confirm!==null} title={confirm==="release"?"Release this appraisal?":confirm==="manager_submit"?"Sign off the manager review?":"Submit your reflection?"} busy={busy} onClose={()=>setConfirm(null)}><p className={styles.muted}>{confirm==="release"?"The employee will be able to see the final assessment, manager notes and development commitments. The signed-off evidence score will remain unchanged.":confirm==="manager_submit"?"Pulse will validate the evidence, freeze a dated snapshot and send this assessment to HR calibration. You cannot edit it again unless HR returns it.":"Your reflection will be sent to the assigned reviewer. You can revise it only if they return it for clarification."}</p><div className={styles.actions}><button className={styles.primary} disabled={busy} onClick={()=>{if(confirm)void act(confirm,confirm==="release"?{rating,rationale}:confirm==="manager_submit"?managerPayload:self).then(ok=>{if(ok)setConfirm(null);});}}><Check size={14} />Confirm {confirm==="release"?"release":"submission"}</button></div></AppraisalDialog>
  </section>;
}
